import Head from "next/head";
import { MobileBio } from "../components/Bio/MobileBio";
import { DesktopBio } from "../components/Bio/DesktopBio";
import { PhotoGrid } from "../components/PhotoGrid/PhotoGrid";
import { TrailerSection } from "../components/TrailerSection/TrailerSection";
import styles from "../styles/Home.module.scss";
import { useState } from "react";
import { useWindowSize } from "../helpers/useWindowSize";

export const Home = () => {
  const size = useWindowSize();
  const [width] = useState(size.width);

  return (
    <div className={styles.container}>
      <Head>
        <title>Honeymoon Missouri Short Film</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/heart-icon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      </Head>

      <div className={styles.main}>
        <div className={styles.titleContainer}>
          <h1 className={styles.title}>Honeymoon Missouri</h1>
        </div>
      </div>
      <div className={`${styles.pane} ${styles.nonBio}`}>
        <div className={styles.paneTextContainer}>
          <h2 className={styles.nonBioTitle}>Log Line</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis
            quo quam, nostrum esse optio placeat incidunt. Maiores ipsa odit
            eveniet excepturi dignissimos ex quos, eos, id consequuntur pariatur
            temporibus iste.
          </p>
        </div>
        <div className={styles.paneTextContainer}>
          <h2 className={styles.nonBioTitle}>Director's Statement</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis
            quo quam, nostrum esse optio placeat incidunt. Maiores ipsa odit
            eveniet excepturi dignissimos ex quos, eos, id consequuntur pariatur
            temporibus iste.
          </p>
        </div>
      </div>
      <TrailerSection variant="tan" />
      {width < 426 || !width ? <DesktopBio /> : <MobileBio />}
      <PhotoGrid
        title="Stills"
        variant="dark"
        useRawImage
        photos={[
          { url: "/Screengrab_1.png" },
          { url: "/Screengrab_2.png" },
          { url: "/Screengrab_3.png" },
          { url: "/Screengrab_4.png" },
          { url: "/Screengrab_5.png" },
        ]}
      />
      <PhotoGrid
        title="Behind the Scenes"
        variant="tan"
        photos={[
          { url: "/bts1.jpg" },
          { url: "/bts2.jpg" },
          { url: "/bts3.jpg" },
          { url: "/bts4.jpg" },
          { url: "/bts5.jpg" },
          { url: "/bts6.jpg" },
          { url: "/bts7.jpg" },
          { url: "/bts8.jpg" },
          { url: "/bts9.jpg" },
          { url: "/bts10.jpg" },
          { url: "/bts11.jpg" },
          { url: "/bts12.jpg" },
        ]}
      />
      <footer className={styles.footer}>
        <div className={styles.footerContent}>
          <h2>Credits</h2>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque
            nostrum repellendus iure natus sunt commodi similique fuga magnam,
            porro optio quasi rerum voluptas id mollitia soluta corporis totam
            debitis amet!
          </p>
        </div>
        <div className={styles.footerContent}>
          <h2>The director wishes to thank:</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim, vel
            voluptatum. Quisquam suscipit vel maxime illum repellat totam
            doloribus rerum neque, dolorem voluptatibus quod repellendus sit
            animi eos quasi excepturi?
          </p>
        </div>
        {/* <div className={styles.footerContent}>
          <h2>With special thanks to:</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum qui
            cupiditate deleniti facilis at natus provident animi ipsum,
            similique molestias sequi modi dicta sapiente consequatur, corporis
            consectetur consequuntur amet quibusdam!
          </p>
        </div> */}
        <div className={styles.footerLogo}>
          <a
            rel="noreferrer"
            target="_blank"
            href="https://www.facebook.com/MissouriMovie/"
          >
            <img src="/facebooklogo.png" alt="" />
          </a>

          <a
            rel="noreferrer"
            target="_blank"
            href="https://www.instagram.com/honeymoonmissourifilm/?hl=en"
          >
            <img src="/instalogo.png" alt="" />
          </a>
        </div>
        <div className={styles.footerLogo}>
          <a href="https://www.imdb.com/title/tt15090714/">
            Visit Honeymoon Missouri on IMDB
          </a>
        </div>
      </footer>
    </div>
  );
};

export default Home;
