import Head from "next/head";
import { MobileBio } from "../components/Bio/MobileBio";
import { DesktopBio } from "../components/Bio/DesktopBio";
import { PhotoGrid } from "../components/PhotoGrid/PhotoGrid";
import { TrailerSection } from "../components/TrailerSection/TrailerSection";
import styles from "../styles/Home.module.scss";
import { useState } from "react";
import { useWindowSize } from "../helpers/useWindowSize";

export const Home = () => {
  const size = useWindowSize();
  const [width] = useState(size.width);

  return (
    <div className={styles.container}>
      <Head>
        <title>Honeymoon Missouri Short Film</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="keywords"
          content="honeymoon missouri, short films, film festival 2022, independent films, joe eckstein, cassie ferrick, george hovis, psychological thriller"
        />
        <meta
          property="og:title"
          content="Honeymoon Missouri - Directed by Joe Eckstein"
        />
        <meta property="og:type" content="video.movie" />
        <meta
          property="og:url"
          content="https://www.honeymoonmissourifilm.com"
        />
        <meta property="og:image" content="/motel-sign.png" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/heart-icon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      </Head>

      <div className={styles.main}>
        <div className={styles.titleContainer}>
          <h1 className={styles.title}>Honeymoon Missouri</h1>
        </div>
      </div>
      <div className={`${styles.pane} ${styles.nonBio}`}>
        <div className={styles.paneTextContainer}>
          <h2 className={styles.nonBioTitle}>Log Line</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis
            quo quam, nostrum esse optio placeat incidunt. Maiores ipsa odit
            eveniet excepturi dignissimos ex quos, eos, id consequuntur pariatur
            temporibus iste.
          </p>
        </div>
        <div className={styles.paneTextContainer}>
          <h2 className={styles.nonBioTitle}>Director's Statement</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis
            quo quam, nostrum esse optio placeat incidunt. Maiores ipsa odit
            eveniet excepturi dignissimos ex quos, eos, id consequuntur pariatur
            temporibus iste.
          </p>
        </div>
      </div>
      <TrailerSection variant="tan" />
      {width < 426 || !width ? <DesktopBio /> : <MobileBio />}
      <PhotoGrid
        title="Stills"
        variant="dark"
        useRawImage
        photos={[
          {
            url: "/Screengrab_1.png",
            alt: "Archie smokes a cigarette outside the motel",
          },
          {
            url: "/Screengrab_2.png",
            alt: "Steve and Debbie Smile towards Archie",
          },
          {
            url: "/Screengrab_3.png",
            alt: "The motel manager smiles towards Archie",
          },
          {
            url: "/Screengrab_4.png",
            alt: "Archie is startled by someone at the door",
          },
          { url: "/Screengrab_5.png", alt: "Archie gets out of her car" },
        ]}
      />
      <PhotoGrid
        title="Behind the Scenes"
        variant="tan"
        photos={[
          { url: "/bts1.jpg", alt: "Joe and Cassie sitting together" },
          {
            url: "/bts2.jpg",
            alt: "Brandan and Joe set up a shot next to Shawn McAninch",
          },
          { url: "/bts3.jpg", alt: "Joe, Cassie, and Brandan set up a scene" },
          {
            url: "/bts4.jpg",
            alt: "The cast and crew of Honeymoon Missouri sit outside talking",
          },
          {
            url: "/bts5.jpg",
            alt: "The cast and crew of Honeymoon Missouri sit down for a table read",
          },
          {
            url: "/bts6.jpg",
            alt: "Joe and Cassie give direction to George Hovis for a scene",
          },
          { url: "/bts7.jpg", alt: "Joe puts a microphone on George Hovis" },
          {
            url: "/bts8.jpg",
            alt: "Joe readsw the script while sitting on a bed of rose petals",
          },
          {
            url: "/bts9.jpg",
            alt: "Brandan films a scene that includes Archie filming Steve and Lorraine dancing",
          },
          {
            url: "/bts10.jpg",
            alt: "Joe looks at the towards the camera while standing next to Brandan",
          },
          {
            url: "/bts11.jpg",
            alt: "Joe looks over the script with Cassie, George Hovis, and Coleen Tutton ",
          },
          {
            url: "/bts12.jpg",
            alt: "The crew films Cassie smoking a cigarette outside the motel",
          },
        ]}
      />
      <footer className={styles.footer}>
        <div className={styles.footerContent}>
          <h2>Credits</h2>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque
            nostrum repellendus iure natus sunt commodi similique fuga magnam,
            porro optio quasi rerum voluptas id mollitia soluta corporis totam
            debitis amet!
          </p>
        </div>
        <div className={styles.footerContent}>
          <h2>The director wishes to thank:</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim, vel
            voluptatum. Quisquam suscipit vel maxime illum repellat totam
            doloribus rerum neque, dolorem voluptatibus quod repellendus sit
            animi eos quasi excepturi?
          </p>
        </div>
        {/* <div className={styles.footerContent}>
          <h2>With special thanks to:</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum qui
            cupiditate deleniti facilis at natus provident animi ipsum,
            similique molestias sequi modi dicta sapiente consequatur, corporis
            consectetur consequuntur amet quibusdam!
          </p>
        </div> */}
        <div className={styles.footerLogo}>
          <a
            rel="noreferrer"
            target="_blank"
            href="https://www.facebook.com/MissouriMovie/"
          >
            <img
              src="/facebooklogo.png"
              alt="Like Honeymoon Missouri on Facebook"
            />
          </a>

          <a
            rel="noreferrer"
            target="_blank"
            href="https://www.instagram.com/honeymoonmissourifilm/?hl=en"
          >
            <img
              src="/instalogo.png"
              alt="Follow Honeymoon Missouri on Instagram"
            />
          </a>
        </div>
        <div className={styles.footerLogo}>
          <a href="https://www.imdb.com/title/tt15090714/">
            Visit Honeymoon Missouri on IMDB
          </a>
        </div>
      </footer>
    </div>
  );
};

export default Home;
